### ISSUE TITLE
To-do's regarding translation

### ISSUE THREAD

**Issue by rene78** [rene78/My-Cryptoportfolio#14]
- [x] Create proper arrow png with transparent background (or even better: svg) and optimize positioning
- [ ] Only show 2-letter language code. But once select list is opened show full language name. Like on [SKD Dresden](https://www.skd.museum/)
- [x] Clean-up CSS
- [x] Describe how to translate app in /data/readme.md

**Comment by rene78** [comment]
Done (except second item).
Solution for 2nd item found but not implemented yet.
Code: https://gist.github.com/rene78/366315bca2250cd8ad5a007425d4f4d5
